import { field } from "./helpers.mjs";

/**
 * Subcategory-specific field sets.
 *
 * These describe only the characteristics that vary between product types. The
 * fields every product has (name, price, stock, images, SEO…) are real columns
 * on `products` and are rendered by the common section of the admin form.
 *
 * `filterable: true` turns a field into a facet on listing pages, and is only
 * meaningful for `select` fields (facets need a bounded set of values).
 * `keySpec: true` promotes the field into the short summary on the product page.
 */
export const fieldSets = [
  {
    key: "generic",
    name: "Caractéristiques générales",
    description: "Jeu de champs par défaut pour les produits sans spécificité forte.",
    fields: [
      field("matiere", "Matière", "text", { keySpec: true }),
      field("couleur", "Couleur", "text", { filterable: false, keySpec: true }),
      field("dimensions", "Dimensions", "text", { placeholder: "L x l x H" }),
      field("contenu", "Contenu de l'emballage", "textarea"),
      field("pays_origine", "Pays d'origine", "text"),
    ],
  },

  // ---------------------------------------------------------------- Computers
  {
    key: "laptop",
    name: "Ordinateur portable",
    fields: [
      field("processeur", "Processeur", "text", { group: "Performance", required: true, keySpec: true, placeholder: "Intel Core i5-1235U" }),
      field("generation_processeur", "Génération du processeur", "text", { group: "Performance" }),
      field("ram", "Mémoire RAM", "select", { group: "Performance", options: ["4 Go", "8 Go", "12 Go", "16 Go", "24 Go", "32 Go", "64 Go"], filterable: true, keySpec: true }),
      field("type_ram", "Type de RAM", "select", { group: "Performance", options: ["DDR3", "DDR4", "DDR5", "LPDDR4X", "LPDDR5"] }),
      field("stockage", "Stockage", "select", { group: "Stockage", options: ["128 Go", "256 Go", "512 Go", "1 To", "2 To"], filterable: true, keySpec: true }),
      field("type_stockage", "Type de stockage", "select", { group: "Stockage", options: ["HDD", "SSD SATA", "SSD NVMe", "eMMC"], filterable: true }),
      field("gpu", "Carte graphique", "text", { group: "Performance", keySpec: true }),
      field("taille_ecran", "Taille de l'écran", "select", { group: "Écran", unit: "pouces", options: ["11.6", "13.3", "14", "15.6", "16", "17.3"], filterable: true, keySpec: true }),
      field("resolution", "Résolution", "select", { group: "Écran", options: ["1366 x 768", "1920 x 1080", "2560 x 1440", "2880 x 1800", "3840 x 2160"] }),
      field("type_ecran", "Type d'écran", "select", { group: "Écran", options: ["TN", "IPS", "OLED", "Tactile"] }),
      field("systeme_exploitation", "Système d'exploitation", "select", { group: "Système", options: ["Windows 11 Famille", "Windows 11 Pro", "Windows 10", "macOS", "Linux", "Sans OS"], filterable: true }),
      field("batterie", "Batterie", "text", { group: "Autonomie", placeholder: "3 cellules, 42 Wh" }),
      field("autonomie", "Autonomie annoncée", "text", { group: "Autonomie", unit: "h" }),
      field("wifi", "Wi-Fi", "select", { group: "Connectivité", options: ["Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7"] }),
      field("bluetooth", "Bluetooth", "text", { group: "Connectivité" }),
      field("ports", "Ports", "textarea", { group: "Connectivité", placeholder: "2x USB-A, 1x USB-C, HDMI, jack 3.5 mm" }),
      field("clavier", "Clavier", "text", { group: "Ergonomie", placeholder: "AZERTY rétroéclairé" }),
      field("webcam", "Webcam", "text", { group: "Ergonomie" }),
      field("poids", "Poids", "number", { group: "Format", unit: "kg" }),
      field("dimensions", "Dimensions", "text", { group: "Format" }),
    ],
  },
  {
    key: "desktop_pc",
    name: "Ordinateur de bureau",
    fields: [
      field("processeur", "Processeur", "text", { required: true, keySpec: true, group: "Performance" }),
      field("ram", "Mémoire RAM", "select", { group: "Performance", options: ["8 Go", "16 Go", "32 Go", "64 Go", "128 Go"], filterable: true, keySpec: true }),
      field("stockage", "Stockage", "text", { group: "Stockage", keySpec: true }),
      field("type_stockage", "Type de stockage", "select", { group: "Stockage", options: ["HDD", "SSD SATA", "SSD NVMe", "Hybride"], filterable: true }),
      field("gpu", "Carte graphique", "text", { group: "Performance", keySpec: true }),
      field("carte_mere", "Carte mère", "text", { group: "Composants" }),
      field("alimentation", "Alimentation", "text", { group: "Composants", unit: "W" }),
      field("boitier", "Format du boîtier", "select", { group: "Composants", options: ["Mini-Tour", "Moyenne Tour", "Grande Tour", "SFF"], filterable: true }),
      field("refroidissement", "Refroidissement", "select", { group: "Composants", options: ["Air", "AIO liquide", "Watercooling custom"] }),
      field("systeme_exploitation", "Système d'exploitation", "select", { group: "Système", options: ["Windows 11 Famille", "Windows 11 Pro", "Linux", "Sans OS"], filterable: true }),
      field("ports", "Ports", "textarea", { group: "Connectivité" }),
      field("reseau", "Réseau", "text", { group: "Connectivité" }),
      field("ecran_inclus", "Écran inclus", "boolean", { group: "Contenu" }),
      field("peripheriques_inclus", "Périphériques inclus", "text", { group: "Contenu" }),
    ],
  },
  {
    key: "mini_pc",
    name: "Mini PC",
    fields: [
      field("processeur", "Processeur", "text", { required: true, keySpec: true }),
      field("ram", "Mémoire RAM", "select", { options: ["4 Go", "8 Go", "16 Go", "32 Go"], filterable: true, keySpec: true }),
      field("stockage", "Stockage", "text", { keySpec: true }),
      field("systeme_exploitation", "Système d'exploitation", "select", { options: ["Windows 11", "Linux", "Sans OS"], filterable: true }),
      field("ports", "Ports", "textarea"),
      field("wifi", "Wi-Fi", "text"),
      field("dimensions", "Dimensions", "text"),
      field("consommation", "Consommation", "number", { unit: "W" }),
    ],
  },

  // --------------------------------------------------------------- Components
  {
    key: "cpu",
    name: "Processeur",
    fields: [
      field("socket", "Socket", "select", { options: ["LGA 1700", "LGA 1851", "LGA 1200", "AM4", "AM5"], filterable: true, required: true, keySpec: true }),
      field("nombre_coeurs", "Nombre de cœurs", "integer", { filterable: false, keySpec: true }),
      field("nombre_threads", "Nombre de threads", "integer" ),
      field("frequence_base", "Fréquence de base", "number", { unit: "GHz", keySpec: true }),
      field("frequence_turbo", "Fréquence turbo", "number", { unit: "GHz" }),
      field("cache", "Cache", "text" ),
      field("tdp", "TDP", "integer", { unit: "W" }),
      field("gpu_integre", "GPU intégré", "text"),
      field("ventirad_inclus", "Ventirad inclus", "boolean"),
    ],
  },
  {
    key: "gpu",
    name: "Carte graphique",
    fields: [
      field("chipset", "Chipset", "text", { required: true, keySpec: true }),
      field("memoire", "Mémoire vidéo", "select", { options: ["4 Go", "6 Go", "8 Go", "12 Go", "16 Go", "24 Go"], filterable: true, keySpec: true }),
      field("type_memoire", "Type de mémoire", "select", { options: ["GDDR5", "GDDR6", "GDDR6X", "GDDR7"] }),
      field("interface", "Interface", "select", { options: ["PCIe 3.0 x16", "PCIe 4.0 x16", "PCIe 5.0 x16"] }),
      field("sorties_video", "Sorties vidéo", "text"),
      field("alimentation_recommandee", "Alimentation recommandée", "integer", { unit: "W" }),
      field("connecteurs_alimentation", "Connecteurs d'alimentation", "text"),
      field("longueur", "Longueur", "number", { unit: "mm" }),
    ],
  },
  {
    key: "motherboard",
    name: "Carte mère",
    fields: [
      field("socket", "Socket", "select", { options: ["LGA 1700", "LGA 1851", "AM4", "AM5"], filterable: true, required: true, keySpec: true }),
      field("chipset", "Chipset", "text", { keySpec: true }),
      field("format", "Format", "select", { options: ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"], filterable: true, keySpec: true }),
      field("type_ram", "Type de RAM", "select", { options: ["DDR4", "DDR5"], filterable: true }),
      field("slots_ram", "Slots mémoire", "integer"),
      field("ram_max", "Mémoire maximale", "text"),
      field("slots_m2", "Slots M.2", "integer"),
      field("ports_sata", "Ports SATA", "integer"),
      field("reseau", "Réseau", "text"),
      field("wifi_integre", "Wi-Fi intégré", "boolean"),
    ],
  },
  {
    key: "ram",
    name: "Mémoire RAM",
    fields: [
      field("capacite", "Capacité", "select", { options: ["4 Go", "8 Go", "16 Go", "32 Go", "64 Go"], filterable: true, required: true, keySpec: true }),
      field("type_ram", "Type", "select", { options: ["DDR3", "DDR4", "DDR5"], filterable: true, keySpec: true }),
      field("frequence", "Fréquence", "integer", { unit: "MHz", keySpec: true }),
      field("latence", "Latence CAS", "text"),
      field("format", "Format", "select", { options: ["DIMM", "SO-DIMM"], filterable: true }),
      field("nombre_barrettes", "Nombre de barrettes", "integer"),
      field("dissipateur", "Dissipateur", "boolean"),
      field("rgb", "Éclairage RGB", "boolean"),
    ],
  },
  {
    key: "storage_drive",
    name: "Disque / SSD",
    fields: [
      field("capacite", "Capacité", "select", { options: ["120 Go", "240 Go", "500 Go", "1 To", "2 To", "4 To", "8 To"], filterable: true, required: true, keySpec: true }),
      field("type_stockage", "Type", "select", { options: ["HDD", "SSD SATA", "SSD NVMe", "SSD externe", "HDD externe"], filterable: true, keySpec: true }),
      field("format", "Format", "select", { options: ['2.5"', '3.5"', "M.2 2280", "M.2 2230"], filterable: true }),
      field("interface", "Interface", "select", { options: ["SATA III", "PCIe 3.0", "PCIe 4.0", "PCIe 5.0", "USB 3.2", "USB-C"] }),
      field("vitesse_lecture", "Vitesse de lecture", "integer", { unit: "Mo/s", keySpec: true }),
      field("vitesse_ecriture", "Vitesse d'écriture", "integer", { unit: "Mo/s" }),
      field("vitesse_rotation", "Vitesse de rotation", "integer", { unit: "tr/min", helpText: "Disques mécaniques uniquement." }),
      field("endurance", "Endurance (TBW)", "text"),
    ],
  },
  {
    key: "psu",
    name: "Alimentation",
    fields: [
      field("puissance", "Puissance", "select", { options: ["450 W", "550 W", "650 W", "750 W", "850 W", "1000 W", "1200 W"], filterable: true, required: true, keySpec: true }),
      field("certification", "Certification", "select", { options: ["80+ White", "80+ Bronze", "80+ Silver", "80+ Gold", "80+ Platinum", "80+ Titanium"], filterable: true, keySpec: true }),
      field("modularite", "Modularité", "select", { options: ["Non modulaire", "Semi-modulaire", "Full modulaire"], filterable: true }),
      field("format", "Format", "select", { options: ["ATX", "SFX", "SFX-L"] }),
      field("connecteurs", "Connecteurs", "textarea"),
      field("ventilateur", "Ventilateur", "text"),
    ],
  },
  {
    key: "pc_case",
    name: "Boîtier PC",
    fields: [
      field("format", "Format", "select", { options: ["Mini-ITX", "Micro-ATX", "Moyenne Tour ATX", "Grande Tour E-ATX"], filterable: true, required: true, keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Acier", "Aluminium", "Verre trempé", "Mesh"], filterable: true }),
      field("ventilateurs_inclus", "Ventilateurs inclus", "integer"),
      field("emplacements_ventilateurs", "Emplacements ventilateurs", "text"),
      field("support_watercooling", "Support watercooling", "text"),
      field("longueur_gpu_max", "Longueur GPU max", "integer", { unit: "mm" }),
      field("hauteur_ventirad_max", "Hauteur ventirad max", "integer", { unit: "mm" }),
      field("ports_facade", "Ports en façade", "text"),
      field("rgb", "Éclairage RGB", "boolean", { filterable: false }),
    ],
  },
  {
    key: "cooling",
    name: "Refroidissement",
    fields: [
      field("type_refroidissement", "Type", "select", { options: ["Ventirad", "AIO 120 mm", "AIO 240 mm", "AIO 280 mm", "AIO 360 mm", "Ventilateur boîtier", "Pâte thermique"], filterable: true, required: true, keySpec: true }),
      field("sockets_compatibles", "Sockets compatibles", "text", { keySpec: true }),
      field("tdp_supporte", "TDP supporté", "integer", { unit: "W" }),
      field("niveau_sonore", "Niveau sonore", "number", { unit: "dB" }),
      field("vitesse_rotation", "Vitesse de rotation", "text", { unit: "tr/min" }),
      field("rgb", "Éclairage RGB", "boolean"),
    ],
  },

  // -------------------------------------------------------------- Peripherals
  {
    key: "keyboard",
    name: "Clavier",
    fields: [
      field("type_clavier", "Type", "select", { options: ["Membrane", "Mécanique", "Optique", "Semi-mécanique"], filterable: true, required: true, keySpec: true }),
      field("format", "Format", "select", { options: ["Complet 100%", "TKL 87%", "75%", "65%", "60%"], filterable: true, keySpec: true }),
      field("disposition", "Disposition", "select", { options: ["AZERTY", "QWERTY", "QWERTZ"], filterable: true }),
      field("connexion", "Connexion", "select", { options: ["Filaire USB", "Sans fil 2.4 GHz", "Bluetooth", "Hybride"], filterable: true, keySpec: true }),
      field("switches", "Switches", "text"),
      field("retroeclairage", "Rétroéclairage", "select", { options: ["Aucun", "Monochrome", "RGB"], filterable: true }),
      field("repose_poignets", "Repose-poignets", "boolean"),
      field("autonomie", "Autonomie", "text"),
    ],
  },
  {
    key: "mouse",
    name: "Souris",
    fields: [
      field("connexion", "Connexion", "select", { options: ["Filaire USB", "Sans fil 2.4 GHz", "Bluetooth", "Hybride"], filterable: true, required: true, keySpec: true }),
      field("capteur", "Capteur", "text"),
      field("dpi_max", "DPI maximum", "integer", { keySpec: true }),
      field("nombre_boutons", "Nombre de boutons", "integer"),
      field("poids", "Poids", "number", { unit: "g" }),
      field("retroeclairage", "Rétroéclairage", "select", { options: ["Aucun", "Monochrome", "RGB"], filterable: true }),
      field("main", "Ergonomie", "select", { options: ["Ambidextre", "Droitier", "Gaucher"], filterable: true }),
      field("autonomie", "Autonomie", "text"),
    ],
  },
  {
    key: "webcam",
    name: "Webcam",
    fields: [
      field("resolution", "Résolution", "select", { options: ["720p", "1080p", "2K", "4K"], filterable: true, required: true, keySpec: true }),
      field("images_par_seconde", "Images par seconde", "select", { options: ["30 fps", "60 fps"], filterable: true, keySpec: true }),
      field("champ_vision", "Champ de vision", "text", { unit: "°" }),
      field("autofocus", "Autofocus", "boolean"),
      field("micro_integre", "Micro intégré", "boolean"),
      field("connexion", "Connexion", "select", { options: ["USB-A", "USB-C"] }),
      field("fixation", "Fixation", "text"),
    ],
  },
  {
    key: "headset",
    name: "Casque audio",
    fields: [
      field("type_casque", "Type", "select", { options: ["Circum-auriculaire", "Supra-auriculaire", "Intra-auriculaire"], filterable: true, required: true, keySpec: true }),
      field("connexion", "Connexion", "select", { options: ["Jack 3.5 mm", "USB", "Sans fil 2.4 GHz", "Bluetooth"], filterable: true, keySpec: true }),
      field("micro", "Microphone", "select", { options: ["Aucun", "Intégré", "Détachable", "Rétractable"], filterable: true }),
      field("reduction_bruit", "Réduction de bruit", "select", { options: ["Aucune", "Passive", "Active (ANC)"], filterable: true }),
      field("son_surround", "Son surround", "text"),
      field("impedance", "Impédance", "text", { unit: "Ω" }),
      field("autonomie", "Autonomie", "text"),
      field("poids", "Poids", "number", { unit: "g" }),
    ],
  },
  {
    key: "speaker",
    name: "Haut-parleurs",
    fields: [
      field("configuration", "Configuration", "select", { options: ["2.0", "2.1", "5.1", "7.1", "Enceinte unique", "Barre de son"], filterable: true, required: true, keySpec: true }),
      field("puissance", "Puissance", "number", { unit: "W RMS", keySpec: true }),
      field("connexion", "Connexion", "select", { options: ["Jack 3.5 mm", "USB", "Bluetooth", "Optique", "HDMI ARC"], filterable: true }),
      field("caisson_basses", "Caisson de basses", "boolean" ),
      field("alimentation", "Alimentation", "select", { options: ["Secteur", "USB", "Batterie"] }),
      field("autonomie", "Autonomie", "text"),
    ],
  },
  {
    key: "microphone",
    name: "Microphone",
    fields: [
      field("type_micro", "Type", "select", { options: ["Dynamique", "À condensateur", "Cravate", "Canon"], filterable: true, required: true, keySpec: true }),
      field("directivite", "Directivité", "select", { options: ["Cardioïde", "Omnidirectionnel", "Bidirectionnel", "Stéréo", "Multiple"], filterable: true, keySpec: true }),
      field("connexion", "Connexion", "select", { options: ["USB", "XLR", "Jack 3.5 mm", "Sans fil"], filterable: true }),
      field("frequence_echantillonnage", "Fréquence d'échantillonnage", "text"),
      field("accessoires_inclus", "Accessoires inclus", "text"),
      field("support", "Support", "text"),
    ],
  },
  {
    key: "usb_flash",
    name: "Clé USB",
    fields: [
      field("capacite", "Capacité", "select", { options: ["8 Go", "16 Go", "32 Go", "64 Go", "128 Go", "256 Go", "512 Go"], filterable: true, required: true, keySpec: true }),
      field("interface", "Interface", "select", { options: ["USB 2.0", "USB 3.0", "USB 3.2", "USB-C", "Double connecteur"], filterable: true, keySpec: true }),
      field("vitesse_lecture", "Vitesse de lecture", "integer", { unit: "Mo/s" }),
      field("materiau", "Matériau", "text"),
      field("etanche", "Résistant à l'eau", "boolean"),
    ],
  },
  {
    key: "memory_card",
    name: "Carte mémoire",
    fields: [
      field("capacite", "Capacité", "select", { options: ["16 Go", "32 Go", "64 Go", "128 Go", "256 Go", "512 Go", "1 To"], filterable: true, required: true, keySpec: true }),
      field("format", "Format", "select", { options: ["microSD", "SD", "CompactFlash", "CFexpress"], filterable: true, keySpec: true }),
      field("classe_vitesse", "Classe de vitesse", "select", { options: ["Class 10", "U1", "U3", "V30", "V60", "V90"], filterable: true }),
      field("vitesse_lecture", "Vitesse de lecture", "integer", { unit: "Mo/s" }),
      field("vitesse_ecriture", "Vitesse d'écriture", "integer", { unit: "Mo/s" }),
      field("adaptateur_inclus", "Adaptateur inclus", "boolean"),
    ],
  },
  {
    key: "monitor",
    name: "Moniteur",
    fields: [
      field("taille_ecran", "Taille de l'écran", "select", { options: ['21.5"', '24"', '27"', '32"', '34"', '49"'], filterable: true, required: true, keySpec: true }),
      field("resolution", "Résolution", "select", { options: ["1920 x 1080", "2560 x 1440", "3440 x 1440", "3840 x 2160"], filterable: true, keySpec: true }),
      field("dalle", "Type de dalle", "select", { options: ["TN", "VA", "IPS", "OLED"], filterable: true, keySpec: true }),
      field("taux_rafraichissement", "Taux de rafraîchissement", "select", { options: ["60 Hz", "75 Hz", "100 Hz", "144 Hz", "165 Hz", "180 Hz", "240 Hz"], filterable: true, keySpec: true }),
      field("temps_reponse", "Temps de réponse", "text", { unit: "ms" }),
      field("connectique", "Connectique", "textarea"),
      field("courbe", "Écran incurvé", "boolean", { filterable: false }),
      field("haut_parleurs", "Haut-parleurs intégrés", "boolean"),
      field("pied_reglable", "Pied réglable", "text"),
      field("compatibilite_vesa", "Compatibilité VESA", "text"),
    ],
  },
  {
    key: "projector",
    name: "Projecteur",
    fields: [
      field("resolution", "Résolution", "select", { options: ["800 x 480", "1280 x 720", "1920 x 1080", "3840 x 2160"], filterable: true, required: true, keySpec: true }),
      field("luminosite", "Luminosité", "integer", { unit: "lumens", keySpec: true }),
      field("technologie", "Technologie", "select", { options: ["LCD", "DLP", "LED", "Laser"], filterable: true }),
      field("contraste", "Contraste", "text"),
      field("distance_projection", "Distance de projection", "text"),
      field("taille_image", "Taille d'image", "text"),
      field("connectique", "Connectique", "textarea"),
      field("duree_lampe", "Durée de vie de la lampe", "text", { unit: "h" }),
      field("haut_parleurs", "Haut-parleurs intégrés", "boolean"),
    ],
  },
  {
    key: "cable",
    name: "Câble / connectique",
    fields: [
      field("type_connecteur_a", "Connecteur A", "text", { required: true, keySpec: true }),
      field("type_connecteur_b", "Connecteur B", "text", { keySpec: true }),
      field("longueur", "Longueur", "select", { options: ["0.5 m", "1 m", "1.5 m", "2 m", "3 m", "5 m", "10 m"], filterable: true, keySpec: true }),
      field("version", "Version / norme", "text", { placeholder: "HDMI 2.1, USB 3.2 Gen 2…" }),
      field("debit", "Débit maximal", "text"),
      field("puissance_charge", "Puissance de charge", "text", { unit: "W" }),
      field("blindage", "Blindage", "text"),
      field("couleur", "Couleur", "text"),
    ],
  },
  {
    key: "network_device",
    name: "Équipement réseau",
    fields: [
      field("type_equipement", "Type d'équipement", "select", { options: ["Routeur", "Switch", "Point d'accès", "Répéteur", "Adaptateur USB", "Carte réseau", "Powerline"], filterable: true, required: true, keySpec: true }),
      field("normes_wifi", "Normes Wi-Fi", "select", { options: ["Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7", "Non applicable"], filterable: true, keySpec: true }),
      field("debit_max", "Débit maximum", "text", { keySpec: true }),
      field("nombre_ports", "Nombre de ports", "integer", { filterable: false }),
      field("vitesse_ports", "Vitesse des ports", "select", { options: ["100 Mb/s", "1 Gb/s", "2.5 Gb/s", "10 Gb/s"], filterable: true }),
      field("gestion", "Gestion", "select", { options: ["Non manageable", "Manageable", "Cloud"] }),
      field("poe", "PoE", "boolean"),
      field("antennes", "Antennes", "text"),
    ],
  },
  {
    key: "printer",
    name: "Imprimante",
    fields: [
      field("technologie", "Technologie", "select", { options: ["Jet d'encre", "Laser monochrome", "Laser couleur", "Sublimation", "Matricielle"], filterable: true, required: true, keySpec: true }),
      field("fonctions", "Fonctions", "select", { options: ["Impression seule", "Multifonction 3-en-1", "Multifonction 4-en-1"], filterable: true, keySpec: true }),
      field("couleur_impression", "Impression couleur", "boolean", { filterable: false, keySpec: true }),
      field("format_max", "Format maximum", "select", { options: ["A4", "A3", "A3+"], filterable: true }),
      field("vitesse_impression", "Vitesse d'impression", "text", { unit: "ppm" }),
      field("resolution_impression", "Résolution", "text", { unit: "dpi" }),
      field("recto_verso", "Recto-verso automatique", "boolean" ),
      field("connectivite", "Connectivité", "textarea"),
      field("capacite_bac", "Capacité du bac", "text", { unit: "feuilles" }),
      field("consommables_compatibles", "Consommables compatibles", "text"),
    ],
  },
  {
    key: "printer_consumable",
    name: "Consommable d'impression",
    fields: [
      field("type_consommable", "Type", "select", { options: ["Cartouche d'encre", "Toner", "Tambour", "Kit de maintenance", "Ruban"], filterable: true, required: true, keySpec: true }),
      field("couleur_consommable", "Couleur", "select", { options: ["Noir", "Cyan", "Magenta", "Jaune", "Tricolore", "Pack multicolore"], filterable: true, keySpec: true }),
      field("reference_constructeur", "Référence constructeur", "text", { keySpec: true }),
      field("imprimantes_compatibles", "Imprimantes compatibles", "textarea"),
      field("rendement", "Rendement", "integer", { unit: "pages" }),
      field("origine", "Origine", "select", { options: ["Original", "Compatible", "Reconditionné"], filterable: true }),
      field("contenance", "Contenance", "text", { unit: "ml" }),
    ],
  },
  {
    key: "calculator",
    name: "Calculatrice",
    fields: [
      field("type_calculatrice", "Type", "select", { options: ["Standard", "Scientifique", "Graphique", "Financière", "De bureau", "À imprimante"], filterable: true, required: true, keySpec: true }),
      field("nombre_fonctions", "Nombre de fonctions", "integer", { keySpec: true }),
      field("affichage", "Affichage", "text", { keySpec: true }),
      field("alimentation", "Alimentation", "select", { options: ["Pile", "Solaire", "Solaire + pile", "Rechargeable"], filterable: true }),
      field("mode_examen", "Mode examen", "boolean"),
      field("programmable", "Programmable", "boolean"),
      field("etui_inclus", "Étui inclus", "boolean"),
      field("dimensions", "Dimensions", "text"),
    ],
  },
  {
    key: "computer_accessory",
    name: "Accessoire informatique",
    fields: [
      field("type_accessoire", "Type d'accessoire", "text", { required: true, keySpec: true }),
      field("compatibilite", "Compatibilité", "text", { keySpec: true }),
      field("connexion", "Connexion", "text"),
      field("materiau", "Matériau", "text"),
      field("couleur", "Couleur", "text"),
      field("dimensions", "Dimensions", "text"),
      field("contenu", "Contenu de l'emballage", "textarea"),
    ],
  },

  // ------------------------------------------------------------ School supply
  {
    key: "writing_instrument",
    name: "Instrument d'écriture",
    fields: [
      field("type_instrument", "Type", "select", { options: ["Stylo bille", "Stylo gel", "Stylo plume", "Roller", "Crayon graphite", "Porte-mine", "Marqueur permanent", "Marqueur effaçable", "Surligneur", "Feutre", "Craie"], filterable: true, required: true, keySpec: true }),
      field("couleur_encre", "Couleur", "select", { options: ["Noir", "Bleu", "Rouge", "Vert", "Assorti", "Multicolore"], filterable: true, keySpec: true }),
      field("epaisseur_trait", "Épaisseur du trait", "text", { unit: "mm", keySpec: true }),
      field("pointe", "Type de pointe", "select", { options: ["Fine", "Moyenne", "Large", "Biseautée", "Ogive"], filterable: true }),
      field("rechargeable", "Rechargeable", "boolean"),
      field("effacable", "Effaçable", "boolean", { filterable: false }),
      field("quantite_lot", "Quantité par lot", "integer", { keySpec: true }),
      field("grip", "Zone de préhension", "text"),
    ],
  },
  {
    key: "notebook",
    name: "Cahier / bloc",
    fields: [
      field("nombre_pages", "Nombre de pages", "integer", { required: true, keySpec: true }),
      field("format", "Format", "select", { options: ["A7", "A6", "A5", "A4", "A3", "17x22", "21x29.7", "24x32"], filterable: true, keySpec: true }),
      field("reglure", "Réglure", "select", { options: ["Seyès", "Ligné", "Quadrillé 5x5", "Petits carreaux", "Uni", "Pointillé", "Musique"], filterable: true, keySpec: true }),
      field("type_papier", "Type de papier", "text"),
      field("grammage", "Grammage", "integer", { unit: "g/m²" }),
      field("couverture", "Couverture", "select", { options: ["Souple", "Rigide", "Polypropylène", "Cartonnée"], filterable: true }),
      field("reliure", "Reliure", "select", { options: ["Agrafée", "Spirale", "Collée", "Cousue"], filterable: true }),
      field("couleur", "Couleur", "text"),
      field("dimensions", "Dimensions", "text"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "art_supply",
    name: "Matériel de dessin et d'art",
    fields: [
      field("type_materiel", "Type de matériel", "select", { options: ["Crayons de couleur", "Crayons de cire", "Pastels", "Peinture", "Pinceaux", "Papier", "Toile", "Kit complet"], filterable: true, required: true, keySpec: true }),
      field("nombre_couleurs", "Nombre de couleurs", "integer", { keySpec: true }),
      field("support", "Support recommandé", "text"),
      field("lavable", "Lavable", "boolean"),
      field("toxicite", "Conformité / non-toxique", "text"),
      field("age_recommande", "Âge recommandé", "text", { filterable: false }),
      field("format", "Format", "text"),
      field("contenu", "Contenu de l'emballage", "textarea"),
    ],
  },
  {
    key: "geometry_tool",
    name: "Instrument de géométrie",
    fields: [
      field("type_instrument", "Type", "select", { options: ["Boîte complète", "Règle", "Équerre", "Rapporteur", "Compas", "Té"], filterable: true, required: true, keySpec: true }),
      field("longueur", "Longueur / taille", "text", { unit: "cm", keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Plastique", "Métal", "Bois", "Aluminium"], filterable: true, keySpec: true }),
      field("graduation", "Graduation", "text"),
      field("contenu", "Contenu de la boîte", "textarea"),
      field("etui_inclus", "Étui inclus", "boolean"),
    ],
  },
  {
    key: "correction_supply",
    name: "Produit de correction",
    fields: [
      field("type_correction", "Type", "select", { options: ["Gomme", "Correcteur liquide", "Correcteur en ruban", "Effaceur", "Stylo correcteur"], filterable: true, required: true, keySpec: true }),
      field("contenance", "Contenance", "text", { unit: "ml", keySpec: true }),
      field("longueur_ruban", "Longueur du ruban", "text", { unit: "m" }),
      field("largeur_ruban", "Largeur du ruban", "text", { unit: "mm" }),
      field("sechage_rapide", "Séchage rapide", "boolean"),
      field("rechargeable", "Rechargeable", "boolean"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "cutting_tool",
    name: "Découpage et taille",
    fields: [
      field("type_outil", "Type", "select", { options: ["Ciseaux scolaires", "Ciseaux de bureau", "Cutter", "Taille-crayon simple", "Taille-crayon double", "Taille-crayon électrique"], filterable: true, required: true, keySpec: true }),
      field("longueur_lame", "Longueur de lame", "text", { unit: "cm", keySpec: true }),
      field("materiau_lame", "Matériau de la lame", "select", { options: ["Acier inoxydable", "Acier carbone", "Plastique"], filterable: true }),
      field("bout_rond", "Bout rond (sécurité enfant)", "boolean"),
      field("reservoir", "Avec réservoir", "boolean"),
      field("gaucher", "Adapté aux gauchers", "boolean"),
      field("age_recommande", "Âge recommandé", "text"),
    ],
  },
  {
    key: "adhesive",
    name: "Colle et adhésif",
    fields: [
      field("type_colle", "Type", "select", { options: ["Colle en bâton", "Colle liquide", "Colle en gel", "Colle forte", "Silicone", "Ruban adhésif", "Pâte adhésive"], filterable: true, required: true, keySpec: true }),
      field("contenance", "Contenance", "text", { unit: "g / ml", keySpec: true }),
      field("supports", "Supports compatibles", "text", { keySpec: true }),
      field("temps_sechage", "Temps de séchage", "text"),
      field("repositionnable", "Repositionnable", "boolean"),
      field("lavable", "Lavable", "boolean"),
      field("sans_solvant", "Sans solvant", "boolean"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "school_kit",
    name: "Trousse et kit scolaire",
    fields: [
      field("type_article", "Type", "select", { options: ["Trousse simple", "Trousse double", "Trousse garnie", "Kit scolaire complet", "Accessoire"], filterable: true, required: true, keySpec: true }),
      field("contenu", "Contenu", "textarea", { keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Polyester", "Toile", "Cuir synthétique", "Plastique", "Métal"], filterable: true }),
      field("nombre_compartiments", "Nombre de compartiments", "integer"),
      field("fermeture", "Fermeture", "select", { options: ["Zip", "Rabat", "Bouton pression", "Élastique"] }),
      field("couleur", "Couleur", "text"),
      field("dimensions", "Dimensions", "text"),
      field("niveau_scolaire", "Niveau scolaire", "select", { options: ["Maternelle", "Primaire", "Collège", "Lycée", "Supérieur"], filterable: true }),
    ],
  },

  // -------------------------------------------------------------------- Gaming
  {
    key: "video_game",
    name: "Jeu vidéo",
    fields: [
      field("plateforme", "Plateforme", "select", { options: ["PC", "PlayStation 5", "PlayStation 4", "Xbox Series X|S", "Xbox One", "Nintendo Switch", "Nintendo Switch 2"], filterable: true, required: true, keySpec: true }),
      field("genre", "Genre", "select", { options: ["Action", "Aventure", "RPG", "FPS", "Sport", "Course", "Stratégie", "Simulation", "Combat", "Famille", "Horreur"], filterable: true, keySpec: true }),
      field("support", "Support", "select", { options: ["Boîte physique", "Clé numérique", "Code de téléchargement"], filterable: true, keySpec: true }),
      field("edition", "Édition", "select", { options: ["Standard", "Deluxe", "Gold", "Ultimate", "Collector"], filterable: true }),
      field("classification", "Classification PEGI", "select", { options: ["PEGI 3", "PEGI 7", "PEGI 12", "PEGI 16", "PEGI 18"], filterable: true }),
      field("langue", "Langues", "text"),
      field("multijoueur", "Multijoueur", "select", { options: ["Solo", "Multijoueur local", "Multijoueur en ligne", "Solo et multijoueur"], filterable: true }),
      field("editeur", "Éditeur", "text"),
      field("date_sortie", "Date de sortie", "date"),
    ],
  },
  {
    key: "gift_card",
    name: "Carte cadeau et abonnement",
    fields: [
      field("plateforme", "Plateforme", "select", { options: ["PlayStation Network", "Xbox", "Nintendo eShop", "Steam", "Google Play", "Apple", "Autre"], filterable: true, required: true, keySpec: true }),
      field("valeur", "Valeur", "text", { keySpec: true }),
      field("duree", "Durée de l'abonnement", "select", { options: ["1 mois", "3 mois", "6 mois", "12 mois", "Sans expiration"], filterable: true, keySpec: true }),
      field("region", "Région", "text", { helpText: "Zone dans laquelle le code est valable." }),
      field("mode_livraison", "Mode de livraison", "select", { options: ["Code par e-mail", "Carte physique"], filterable: true }),
      field("conditions", "Conditions d'utilisation", "textarea"),
    ],
  },
  {
    key: "console",
    name: "Console de jeu",
    fields: [
      field("marque_console", "Famille de console", "select", { options: ["PlayStation", "Xbox", "Nintendo", "Rétro", "Portable Android", "Autre"], filterable: true, required: true, keySpec: true }),
      field("modele_console", "Modèle", "text", { keySpec: true }),
      field("stockage", "Stockage", "select", { options: ["64 Go", "256 Go", "512 Go", "825 Go", "1 To", "2 To"], filterable: true, keySpec: true }),
      field("lecteur_disque", "Lecteur de disque", "boolean", { filterable: false, keySpec: true }),
      field("resolution_max", "Résolution maximale", "select", { options: ["1080p", "1440p", "4K", "8K"], filterable: true }),
      field("manettes_incluses", "Manettes incluses", "integer"),
      field("jeux_inclus", "Jeux inclus", "text"),
      field("etat", "État", "select", { options: ["Neuf", "Reconditionné"], filterable: true }),
      field("contenu", "Contenu de la boîte", "textarea"),
    ],
  },
  {
    key: "gaming_controller",
    name: "Manette",
    fields: [
      field("plateforme", "Plateforme", "select", { options: ["PlayStation 5", "PlayStation 4", "Xbox Series X|S", "Xbox One", "Nintendo Switch", "PC", "Multiplateforme"], filterable: true, required: true, keySpec: true }),
      field("compatibilite", "Compatibilité", "text", { keySpec: true }),
      field("connexion", "Connexion", "select", { options: ["Filaire USB", "Sans fil 2.4 GHz", "Bluetooth", "Hybride"], filterable: true, keySpec: true }),
      field("bluetooth", "Bluetooth", "boolean"),
      field("usb", "USB", "select", { options: ["USB-A", "USB-C", "Non applicable"] }),
      field("sans_fil", "Sans fil", "boolean", { filterable: false }),
      field("batterie", "Batterie", "select", { options: ["Rechargeable intégrée", "Piles AA", "Batterie amovible", "Filaire"], filterable: true }),
      field("autonomie", "Autonomie", "text", { unit: "h" }),
      field("vibration", "Retour haptique / vibration", "select", { options: ["Aucun", "Vibration simple", "Retour haptique avancé", "Gâchettes adaptatives"], filterable: true }),
      field("couleur", "Couleur", "text"),
      field("poids", "Poids", "number", { unit: "g" }),
      field("boutons_programmables", "Boutons programmables", "boolean"),
    ],
  },
  {
    key: "gaming_peripheral",
    name: "Périphérique gaming",
    fields: [
      field("type_peripherique", "Type", "select", { options: ["Volant", "Pédalier", "Levier de vitesse", "Joystick", "Palonnier", "Arcade stick"], filterable: true, required: true, keySpec: true }),
      field("plateforme", "Plateformes compatibles", "text", { keySpec: true }),
      field("retour_force", "Retour de force", "select", { options: ["Aucun", "Vibration", "Retour de force", "Direct Drive"], filterable: true, keySpec: true }),
      field("angle_rotation", "Angle de rotation", "text", { unit: "°" }),
      field("materiau", "Matériau", "text"),
      field("fixation", "Fixation", "text"),
      field("pedales_incluses", "Pédalier inclus", "boolean"),
    ],
  },
  {
    key: "gaming_furniture",
    name: "Mobilier gaming",
    fields: [
      field("type_mobilier", "Type", "select", { options: ["Fauteuil gaming", "Chaise de bureau", "Bureau gaming", "Support écran", "Support casque"], filterable: true, required: true, keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Similicuir", "Tissu", "Mesh", "Bois", "Métal", "Verre trempé"], filterable: true, keySpec: true }),
      field("charge_max", "Charge maximale", "integer", { unit: "kg", keySpec: true }),
      field("reglages", "Réglages", "textarea"),
      field("inclinaison", "Inclinaison du dossier", "text", { unit: "°" }),
      field("accoudoirs", "Accoudoirs", "select", { options: ["Fixes", "2D", "3D", "4D", "Sans accoudoirs"], filterable: true }),
      field("dimensions_plateau", "Dimensions du plateau", "text"),
      field("hauteur_reglable", "Hauteur réglable", "boolean"),
      field("couleur", "Couleur", "text"),
      field("montage_requis", "Montage requis", "boolean"),
    ],
  },
  {
    key: "gaming_accessory",
    name: "Accessoire gaming",
    fields: [
      field("type_accessoire", "Type d'accessoire", "text", { required: true, keySpec: true }),
      field("plateforme", "Plateformes compatibles", "text", { keySpec: true }),
      field("connexion", "Connexion", "text"),
      field("rgb", "Éclairage RGB", "boolean", { filterable: false }),
      field("dimensions", "Dimensions", "text"),
      field("materiau", "Matériau", "text"),
      field("couleur", "Couleur", "text"),
      field("contenu", "Contenu de l'emballage", "textarea"),
    ],
  },

  // -------------------------------------------------------------------- Office
  {
    key: "filing_supply",
    name: "Classement et organisation",
    fields: [
      field("type_classement", "Type", "select", { options: ["Classeur à levier", "Classeur à anneaux", "Chemise", "Sous-chemise", "Dossier suspendu", "Porte-documents", "Boîte de classement", "Trieur"], filterable: true, required: true, keySpec: true }),
      field("format", "Format", "select", { options: ["A4", "A5", "A3", "Folio"], filterable: true, keySpec: true }),
      field("capacite", "Capacité", "text", { unit: "feuilles", keySpec: true }),
      field("dos", "Largeur du dos", "text", { unit: "mm" }),
      field("materiau", "Matériau", "select", { options: ["Carton", "Carton plastifié", "Polypropylène", "Kraft"], filterable: true }),
      field("nombre_anneaux", "Nombre d'anneaux", "integer"),
      field("couleur", "Couleur", "text"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "stapler",
    name: "Agrafage",
    fields: [
      field("type_agrafage", "Type", "select", { options: ["Agrafeuse de bureau", "Agrafeuse pince", "Agrafeuse longue portée", "Agrafes", "Dégrafeuse"], filterable: true, required: true, keySpec: true }),
      field("capacite_agrafage", "Capacité d'agrafage", "integer", { unit: "feuilles", keySpec: true }),
      field("type_agrafes", "Type d'agrafes", "select", { options: ["24/6", "26/6", "23/8", "23/10", "No 10"], filterable: true, keySpec: true }),
      field("materiau", "Matériau", "text"),
      field("quantite_lot", "Quantité par boîte", "integer"),
      field("couleur", "Couleur", "text"),
    ],
  },
  {
    key: "office_adhesive",
    name: "Adhésif de bureau",
    fields: [
      field("type_adhesif", "Type", "select", { options: ["Ruban transparent", "Ruban d'emballage", "Ruban de masquage", "Ruban double-face", "Dévidoir"], filterable: true, required: true, keySpec: true }),
      field("largeur", "Largeur", "text", { unit: "mm", keySpec: true }),
      field("longueur", "Longueur", "text", { unit: "m", keySpec: true }),
      field("couleur", "Couleur", "text"),
      field("repositionnable", "Repositionnable", "boolean"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "fastener",
    name: "Fixation",
    fields: [
      field("type_fixation", "Type", "select", { options: ["Trombone", "Pince double-clip", "Élastique", "Punaise", "Crochet adhésif", "Attache-lettre"], filterable: true, required: true, keySpec: true }),
      field("taille", "Taille", "text", { unit: "mm", keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Métal", "Métal gainé", "Plastique", "Caoutchouc"], filterable: true }),
      field("quantite_lot", "Quantité par boîte", "integer", { keySpec: true }),
      field("couleur", "Couleur", "text"),
      field("charge_max", "Charge maximale", "text", { unit: "kg" }),
    ],
  },
  {
    key: "office_paper",
    name: "Papeterie",
    fields: [
      field("type_papier", "Type", "select", { options: ["Papier d'impression", "Bloc-notes", "Post-it", "Enveloppe", "Papier couleur", "Papier photo"], filterable: true, required: true, keySpec: true }),
      field("format", "Format", "select", { options: ["A6", "A5", "A4", "A3", "DL", "C5", "C4"], filterable: true, keySpec: true }),
      field("grammage", "Grammage", "select", { options: ["70 g/m²", "80 g/m²", "90 g/m²", "100 g/m²", "120 g/m²", "160 g/m²", "200 g/m²"], filterable: true, keySpec: true }),
      field("quantite", "Quantité", "integer", { unit: "feuilles", keySpec: true }),
      field("blancheur", "Blancheur / couleur", "text"),
      field("fenetre", "Avec fenêtre", "boolean"),
      field("fermeture", "Fermeture", "text"),
      field("certification", "Certification environnementale", "text"),
    ],
  },
  {
    key: "stamp",
    name: "Tampon et cachet",
    fields: [
      field("type_tampon", "Type", "select", { options: ["Tampon auto-encreur", "Tampon bois", "Tampon dateur", "Tampon personnalisable", "Encreur", "Recharge d'encre"], filterable: true, required: true, keySpec: true }),
      field("personnalisable", "Personnalisable", "boolean", { keySpec: true }),
      field("nombre_lignes", "Nombre de lignes", "integer"),
      field("dimensions_empreinte", "Dimensions de l'empreinte", "text", { keySpec: true }),
      field("couleur_encre", "Couleur d'encre", "select", { options: ["Noir", "Bleu", "Rouge", "Vert", "Violet"], filterable: true }),
      field("nombre_empreintes", "Nombre d'empreintes", "text"),
    ],
  },
  {
    key: "office_accessory",
    name: "Accessoire de bureau",
    fields: [
      field("type_accessoire", "Type d'accessoire", "text", { required: true, keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Plastique", "Métal", "Bois", "Verre", "Cuir synthétique"], filterable: true, keySpec: true }),
      field("nombre_compartiments", "Nombre de compartiments", "integer"),
      field("couleur", "Couleur", "text"),
      field("dimensions", "Dimensions", "text"),
      field("contenu", "Contenu de l'emballage", "textarea"),
    ],
  },

  // ---------------------------------------------------------- Home & groceries
  {
    key: "cleaning_product",
    name: "Produit ménager",
    fields: [
      field("type_produit", "Type de produit", "select", { options: ["Nettoyant multi-surfaces", "Désinfectant", "Lessive", "Adoucissant", "Liquide vaisselle", "Détartrant", "Javel", "Entretien sol"], filterable: true, required: true, keySpec: true }),
      field("contenance", "Contenance", "text", { unit: "L / kg", keySpec: true }),
      field("forme", "Forme", "select", { options: ["Liquide", "Poudre", "Gel", "Capsules", "Spray", "Lingettes"], filterable: true, keySpec: true }),
      field("parfum", "Parfum", "text"),
      field("surfaces", "Surfaces compatibles", "text"),
      field("mode_utilisation", "Mode d'utilisation", "textarea"),
      field("precautions", "Précautions d'emploi", "textarea"),
      field("ecologique", "Formule écologique", "boolean"),
      field("nombre_doses", "Nombre de doses / lavages", "integer"),
    ],
  },
  {
    key: "kitchenware",
    name: "Ustensile de cuisine",
    fields: [
      field("type_ustensile", "Type", "text", { required: true, keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Inox", "Aluminium", "Plastique alimentaire", "Silicone", "Bois", "Céramique", "Verre", "Fonte"], filterable: true, keySpec: true }),
      field("capacite", "Capacité", "text", { unit: "L", keySpec: true }),
      field("dimensions", "Dimensions", "text"),
      field("compatible_lave_vaisselle", "Compatible lave-vaisselle", "boolean", { filterable: false }),
      field("compatible_induction", "Compatible induction", "boolean", { filterable: false }),
      field("passe_au_four", "Passe au four", "boolean"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "storage_container",
    name: "Rangement et contenant",
    fields: [
      field("type_rangement", "Type", "select", { options: ["Boîte hermétique", "Boîte de rangement", "Panier", "Bac", "Organisateur", "Crochet", "Étagère"], filterable: true, required: true, keySpec: true }),
      field("capacite", "Capacité", "text", { unit: "L", keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Plastique", "Verre", "Inox", "Osier", "Tissu", "Bambou"], filterable: true, keySpec: true }),
      field("hermetique", "Hermétique", "boolean"),
      field("empilable", "Empilable", "boolean"),
      field("dimensions", "Dimensions", "text"),
      field("couleur", "Couleur", "text"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "lighting",
    name: "Éclairage",
    fields: [
      field("type_eclairage", "Type", "select", { options: ["Ampoule LED", "Ampoule rechargeable", "Tube LED", "Lampe de bureau", "Lampe torche", "Projecteur", "Guirlande", "Applique"], filterable: true, required: true, keySpec: true }),
      field("culot", "Culot", "select", { options: ["E27", "E14", "B22", "GU10", "G9", "Non applicable"], filterable: true, keySpec: true }),
      field("puissance", "Puissance", "text", { unit: "W", keySpec: true }),
      field("flux_lumineux", "Flux lumineux", "integer", { unit: "lumens" }),
      field("temperature_couleur", "Température de couleur", "select", { options: ["Blanc chaud (2700K)", "Blanc neutre (4000K)", "Blanc froid (6500K)", "RGB"], filterable: true }),
      field("autonomie", "Autonomie", "text", { unit: "h", helpText: "Modèles rechargeables uniquement." }),
      field("duree_vie", "Durée de vie", "text", { unit: "h" }),
      field("dimmable", "Variable (dimmable)", "boolean"),
      field("etanche", "Indice de protection", "text"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },
  {
    key: "battery",
    name: "Pile et batterie",
    fields: [
      field("format_pile", "Format", "select", { options: ["AA (LR6)", "AAA (LR03)", "C (LR14)", "D (LR20)", "9V (6LR61)", "Bouton CR2032", "18650", "Batterie externe"], filterable: true, required: true, keySpec: true }),
      field("technologie", "Technologie", "select", { options: ["Alcaline", "Lithium", "NiMH rechargeable", "Li-ion", "Zinc-carbone"], filterable: true, keySpec: true }),
      field("capacite", "Capacité", "text", { unit: "mAh", keySpec: true }),
      field("tension", "Tension", "text", { unit: "V" }),
      field("rechargeable", "Rechargeable", "boolean", { filterable: false }),
      field("nombre_cycles", "Nombre de cycles", "integer"),
      field("quantite_lot", "Quantité par lot", "integer", { keySpec: true }),
      field("date_expiration", "Date limite d'utilisation", "date"),
    ],
  },
  {
    key: "food",
    name: "Produit alimentaire",
    fields: [
      field("type_aliment", "Type de produit", "select", { options: ["Snack salé", "Biscuit", "Bonbon", "Chocolat", "Boisson gazeuse", "Jus", "Eau", "Café", "Thé", "Épicerie sèche", "Conserve"], filterable: true, required: true, keySpec: true }),
      field("poids_volume", "Poids / volume net", "text", { unit: "g / ml", required: true, keySpec: true }),
      field("ingredients", "Ingrédients", "textarea", { required: true }),
      field("allergenes", "Allergènes", "textarea", { helpText: "Mentionner clairement gluten, arachides, lait, œufs, fruits à coque…", keySpec: true }),
      field("valeurs_nutritionnelles", "Valeurs nutritionnelles", "textarea", { helpText: "Pour 100 g ou 100 ml." }),
      field("date_fabrication", "Date de fabrication", "date"),
      field("date_expiration", "Date de péremption", "date", { required: true, keySpec: true }),
      field("conditions_conservation", "Conditions de conservation", "textarea"),
      field("pays_origine", "Pays d'origine", "text", { filterable: false }),
      field("informations_supplementaires", "Informations supplémentaires", "textarea"),
      field("quantite_lot", "Quantité par lot", "integer"),
    ],
  },

  // ---------------------------------------------------------------- Cosmetics
  {
    key: "cosmetic",
    name: "Produit cosmétique",
    fields: [
      field("type_produit", "Type de produit", "select", { options: ["Nettoyant", "Crème", "Sérum", "Masque", "Lotion", "Huile", "Savon", "Gommage", "Shampooing", "Après-shampooing", "Produit coiffant"], filterable: true, required: true, keySpec: true }),
      field("volume_poids", "Volume / poids", "text", { unit: "ml / g", required: true, keySpec: true }),
      field("type_peau", "Type de peau / cheveux", "select", { options: ["Tous types", "Peau sèche", "Peau grasse", "Peau mixte", "Peau sensible", "Cheveux secs", "Cheveux gras", "Cheveux bouclés", "Cheveux colorés"], filterable: true, keySpec: true }),
      field("parfum", "Parfum", "text"),
      field("ingredients", "Ingrédients (INCI)", "textarea", { required: true }),
      field("mode_utilisation", "Mode d'utilisation", "textarea"),
      field("precautions", "Précautions", "textarea"),
      field("date_expiration", "Date d'expiration", "date"),
      field("pao", "PAO (durée après ouverture)", "text", { placeholder: "12M" }),
      field("pays_origine", "Pays d'origine", "text"),
      field("bio", "Certifié bio", "boolean", { filterable: false }),
    ],
  },
  {
    key: "fragrance",
    name: "Parfumerie",
    fields: [
      field("type_parfum", "Type", "select", { options: ["Eau de parfum", "Eau de toilette", "Eau de cologne", "Brume corporelle", "Déodorant spray", "Déodorant stick", "Déodorant roll-on"], filterable: true, required: true, keySpec: true }),
      field("volume", "Volume", "select", { options: ["30 ml", "50 ml", "75 ml", "100 ml", "150 ml", "200 ml"], filterable: true, keySpec: true }),
      field("genre", "Pour", "select", { options: ["Femme", "Homme", "Mixte"], filterable: true, keySpec: true }),
      field("famille_olfactive", "Famille olfactive", "select", { options: ["Florale", "Boisée", "Orientale", "Fraîche", "Fruitée", "Épicée", "Aromatique"], filterable: true }),
      field("notes_tete", "Notes de tête", "text"),
      field("notes_coeur", "Notes de cœur", "text"),
      field("notes_fond", "Notes de fond", "text"),
      field("tenue", "Tenue", "text", { unit: "h" }),
      field("ingredients", "Ingrédients", "textarea"),
      field("precautions", "Précautions", "textarea"),
    ],
  },
  {
    key: "makeup",
    name: "Maquillage",
    fields: [
      field("zone", "Zone", "select", { options: ["Lèvres", "Yeux", "Teint", "Ongles", "Sourcils"], filterable: true, required: true, keySpec: true }),
      field("type_produit", "Type de produit", "text", { required: true, keySpec: true }),
      field("teinte", "Teinte", "text", { keySpec: true }),
      field("fini", "Fini", "select", { options: ["Mat", "Satiné", "Brillant", "Nacré", "Poudré"], filterable: true }),
      field("volume_poids", "Volume / poids", "text", { unit: "ml / g" }),
      field("type_peau", "Type de peau", "select", { options: ["Tous types", "Peau sèche", "Peau grasse", "Peau mixte", "Peau sensible"], filterable: true }),
      field("longue_tenue", "Longue tenue", "boolean"),
      field("waterproof", "Waterproof", "boolean", { filterable: false }),
      field("ingredients", "Ingrédients", "textarea"),
      field("mode_utilisation", "Mode d'utilisation", "textarea"),
      field("date_expiration", "Date d'expiration", "date"),
    ],
  },
  {
    key: "beauty_accessory",
    name: "Accessoire beauté",
    fields: [
      field("type_accessoire", "Type d'accessoire", "select", { options: ["Miroir", "Trousse", "Pinceau", "Éponge", "Lime", "Coupe-ongles", "Brosse", "Peigne", "Set de soin"], filterable: true, required: true, keySpec: true }),
      field("materiau", "Matériau", "text", { keySpec: true }),
      field("dimensions", "Dimensions", "text"),
      field("couleur", "Couleur", "text"),
      field("grossissement", "Grossissement", "text", { helpText: "Miroirs uniquement." }),
      field("eclairage_led", "Éclairage LED", "boolean"),
      field("contenu", "Contenu du set", "textarea"),
    ],
  },

  // --------------------------------------------------------- Sports & leisure
  {
    key: "sports_equipment",
    name: "Équipement sportif",
    fields: [
      field("sport", "Sport", "select", { options: ["Football", "Basketball", "Fitness", "Musculation", "Course", "Yoga", "Natation", "Tennis", "Cyclisme", "Multisport"], filterable: true, required: true, keySpec: true }),
      field("type_equipement", "Type d'équipement", "text", { required: true, keySpec: true }),
      field("taille", "Taille", "text", { keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Cuir", "Synthétique", "PVC", "Caoutchouc", "Acier", "Néoprène", "Mousse"], filterable: true }),
      field("poids", "Poids", "number", { unit: "kg" }),
      field("niveau", "Niveau", "select", { options: ["Débutant", "Intermédiaire", "Confirmé", "Compétition"], filterable: true }),
      field("usage", "Usage", "select", { options: ["Intérieur", "Extérieur", "Intérieur et extérieur"], filterable: true }),
      field("contenu", "Contenu", "textarea"),
    ],
  },
  {
    key: "sports_apparel",
    name: "Vêtement de sport",
    fields: [
      field("type_vetement", "Type", "select", { options: ["Maillot", "Short", "Survêtement", "T-shirt", "Chaussettes", "Legging", "Veste", "Brassière"], filterable: true, required: true, keySpec: true }),
      field("taille", "Taille", "select", { options: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "Enfant"], filterable: true, keySpec: true }),
      field("genre", "Pour", "select", { options: ["Homme", "Femme", "Enfant", "Mixte"], filterable: true, keySpec: true }),
      field("couleur", "Couleur", "text", { keySpec: true }),
      field("matiere", "Matière", "select", { options: ["Polyester", "Coton", "Coton mélangé", "Élasthanne", "Mesh technique"], filterable: true }),
      field("respirant", "Tissu respirant", "boolean"),
      field("equipe", "Équipe / club", "text"),
      field("saison", "Saison", "text"),
      field("entretien", "Conseils d'entretien", "text"),
    ],
  },
  {
    key: "footwear",
    name: "Chaussures",
    fields: [
      field("type_chaussure", "Type", "select", { options: ["Crampons gazon", "Crampons synthétique", "Chaussures de salle", "Running", "Fitness", "Basketball"], filterable: true, required: true, keySpec: true }),
      field("pointure", "Pointure", "select", { options: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"], filterable: true, keySpec: true }),
      field("genre", "Pour", "select", { options: ["Homme", "Femme", "Enfant", "Mixte"], filterable: true, keySpec: true }),
      field("couleur", "Couleur", "text"),
      field("matiere_dessus", "Matière du dessus", "text"),
      field("type_semelle", "Type de semelle", "text"),
      field("fermeture", "Fermeture", "select", { options: ["Lacets", "Scratch", "Sans lacets", "Élastique"] }),
      field("poids", "Poids", "number", { unit: "g" }),
    ],
  },
  {
    key: "board_game",
    name: "Jeu de société",
    fields: [
      field("type_jeu", "Type de jeu", "select", { options: ["Échecs", "Dames", "Ludo", "Jeu de cartes", "Stratégie", "Ambiance", "Familial", "Coopératif", "Dominos", "Scrabble"], filterable: true, required: true, keySpec: true }),
      field("nombre_joueurs", "Nombre de joueurs", "select", { options: ["1 joueur", "2 joueurs", "2 à 4 joueurs", "2 à 6 joueurs", "3 à 8 joueurs", "8 joueurs et plus"], filterable: true, keySpec: true }),
      field("age_minimum", "Âge minimum", "select", { options: ["3 ans et +", "6 ans et +", "8 ans et +", "10 ans et +", "12 ans et +", "16 ans et +"], filterable: true, keySpec: true }),
      field("duree_partie", "Durée d'une partie", "text", { unit: "min" }),
      field("materiau", "Matériau", "select", { options: ["Bois", "Plastique", "Carton", "Métal", "Magnétique"], filterable: true }),
      field("langue", "Langue", "text"),
      field("contenu", "Contenu de la boîte", "textarea"),
      field("dimensions", "Dimensions", "text"),
    ],
  },
  {
    key: "toy",
    name: "Jeu et loisir",
    fields: [
      field("type_jouet", "Type", "select", { options: ["Puzzle", "Jeu éducatif", "Jeu d'éveil", "Jeu de construction", "Jeu d'extérieur", "Jeu d'adresse", "Figurine"], filterable: true, required: true, keySpec: true }),
      field("age_recommande", "Âge recommandé", "select", { options: ["0-2 ans", "3-5 ans", "6-8 ans", "9-11 ans", "12 ans et +"], filterable: true, keySpec: true }),
      field("nombre_pieces", "Nombre de pièces", "integer", { keySpec: true }),
      field("materiau", "Matériau", "select", { options: ["Bois", "Plastique", "Carton", "Tissu", "Mousse"], filterable: true }),
      field("competences", "Compétences développées", "text"),
      field("piles_requises", "Piles requises", "boolean"),
      field("dimensions", "Dimensions", "text"),
      field("securite", "Normes de sécurité", "text"),
    ],
  },
];
